### ISSUE TITLE
Create a project page

### ISSUE THREAD

**Issue by KeizerDev** [KeizerDev/Browsertime#10]
On the `gh-pages` branch:
- Install guide/scripts
- Show actual screenshots of the browsertime
- FAQ
- Donation

**Comment by fritek373** [comment]
You need to say that it's only for developers (in the first line), to prevent all kind of stupid questions (Like what is happening on Reddit now).

**Comment by KeizerDev** [comment]
@fritek373 Actually it have to be hosted somewhere but I don't want to do that. So that would be a developer guide yeah. I'll probably will make some build scripts for different distros so it is super easy to build and deploy for the world

**Comment by fritek373** [comment]
Yup, sounds like a good idea. Don't host it yourself, make the users host it. Installations should be easy as well, but how?

**Comment by KeizerDev** [comment]
I'll make some bash scripts for different linux distro's

**Comment by lbennett-stacki** [comment]
What about implementing [peercloud](https://github.com/jhiesey/peercloud) allowing the users of Browsertime to host the publicly hosted websites? This does however raise a question...

If everyone has to download the repo and run the local server application in order to use the player in the browser, why isn't it just packaged and distributed as a desktop application? The beauty of browser applications is their availability and ease of use but with this in mind Browsertime certainly better suites an [electron](https://github.com/atom/electron) application over a browser application. Which brings us back to essentially rebuilding popcorntime and thus something magical has to happen in issue #7 to get this moving.

Another alternative could be to use [peercloud](https://github.com/jhiesey/peercloud) to build a "daemon" application which allows peers to opt-in and download a small server application in order to help host the public websites that run the Browsertime scripts. You could maybe even offer bonuses to "seeders" or go a step further and only allow access to the site if the daemon is found running on their local system.

I could be looking at this completely wrong though, what do you think?

**Comment by KeizerDev** [comment]
@LukeeeeBennett Sorry for my late response, I won't be able to host this myself because of #7. What I want users who can host this frontend. I'll create an electron app to just seed the movies to the webtorrent protocol and use a tracker to index those so we can use this in the browser(front end version). The hardest thing is to reseed everything for the web. I can't do this on my own. 

We can start with like 5 movies, hosted on a digital ocean server to make this project more public and just get started with it. Than eventually, people will add movies to it, I hope. If we can just make something to index those movies and wrap it to one api we are gtg. 

The hosting part is just a pain in the ass for me. Let's just pretend that browsertime is an frontend for a webbased torrent protocol. I think that would make a lot clear to you. 

You can mail me or pm me on gitter so we can talk a bit further if you want.
